AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  UseCache: false

# Avoid checking for "Missing top-level documentation"
Documentation:
  Enabled: false

# Allow lines of code up to X characters
Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: single_quotes
