AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  UseCache: false

# Avoid checking for "Missing top-level documentation"
Documentation:
  Enabled: false

# Allow lines of code up to X characters
Metrics/LineLength:
  Max: 120
