language: ruby
rvm:
  - 2.3.0

services:
  - postgresql

addons:
  postgresql: "9.3"

# Setup Test Database
before_script:
  - psql -c 'create database sailorboy_test;' -U postgres
  - rake db:schema:load
